[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov"
testpaths = ["tests"]
pythonpath = ["."]

[project]
name = "codeowners"
version = "2.1.0"
requires-python = ">=3.9"
dependencies = [
    "attrs",
    "jsonschema",
    "jsonschema-specifications",
    "referencing",
    "rpds-py",
]

[project.scripts]
codeowners = "codeowners.__main__:main"

[tool.setuptools]
packages = ["codeowners"]

[tool.isort]
profile = "black"

[tool.ruff.lint]
pydocstyle.convention = "google"
select = [
    "RUF", # Ruff-specific rules
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "D",   # pydocstyle
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "C",   # flake8-comprehensions
    "B",   # flake8-bugbear
    "ANN", # flake8-annotations
    "S",   # flake8-bandit
    "PL",  # Pylint
    "TRY", # tryceratops
    "EM",  # flake8-errmsg
    "C4",  # flake8-comprehensions
    "Q",   # flake8-quotes
    "SIM", # flake8-simplify
    "PTH", # flake8-use-pathlib
]
ignore = [
    "D100",    # Missing docstring in public module
    "D101",    # Missing docstring in public class
    "D104",    # Missing docstring in public package
    "D107",    # Missing docstring in `__init__`
    "S603",    # `subprocess` call: check for execution of untrusted input
    "S607",    # Starting a process with a partial executable path
]
